### ISSUE TITLE
The background is to long and I'm not sure how to fix it

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/responsive-icon-cards#1]
@Thomasjbradley

I need to make the length of my website smaller but I can't remember what to do, because when I bring it into markbot it's too long.

**Comment by thomasjbradley** [comment]
I’m not entirely sure what you mean. Is it related to fixing the margins on the elements?

**Comment by fuen0015** [comment]
In CSS I need to adjust the bottom of the page because it's pushed down or to big but I'm not sure where to do that.

**Comment by fuen0015** [comment]
<img width="366" alt="screen shot 2018-11-21 at 7 56 22 pm" src="https://user-images.githubusercontent.com/43240727/48875562-a0fcd880-edc7-11e8-91c7-b2a15f67208d.png">

**Comment by fuen0015** [comment]
Updated version
![image](https://user-images.githubusercontent.com/43240727/48908095-616dd500-ee37-11e8-8641-5c6ec366f604.png)
